#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_mysql_db_shell < $install_dir/src/install/sql/sample_data.sql

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="environment.php" --destination="$install_dir/src/config/environment.php"

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression "Setting up application with CURL..."

ynh_local_curl "/install/setup.php"

ynh_safe_rm "$install_dir/src/install"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
