#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir/sql/" --source_id="db"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="environment.php" --destination="$install_dir/src/config/environment.php"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression "Setting up application with CURL..."

ynh_replace --match="#prefix#" --replace="qr_" --file="$install_dir/sql/sample_data.sql"

ynh_mysql_db_shell < $install_dir/sql/sample_data.sql

#ynh_local_curl "/install/setup.php"

#ynh_safe_rm "$install_dir/sql/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
